### ISSUE TITLE
Usage for Melodic

### ISSUE THREAD

**Issue by Jornsd** [Interbotix/kinematics_from_description#2]
Is it possible to use this package for Melodic? If so, how?

**Comment by lukeschmitt-tr** [comment]
You can use this package if you have Python3 installed. Use the [requirements.txt](https://github.com/Interbotix/kinematics_from_description/blob/c53893dbc289f959db907814e5cd2069c0ff94d3/requirements.txt) file to install the required dependencies and run it using the [Importing method](https://github.com/Interbotix/kinematics_from_description#importing).

**Comment by Jornsd** [comment]
Thank you for helping! I had no issue with installing the dependencies, but could you provide some more instructions on how to run is using the Import method?

**Comment by lukeschmitt-tr** [comment]
Load your robot_description parameter into the ROS parameter server. For example, running the command below will put the wx200's robot_description into the parameter server under the namespace `/wx200`.
```console
$ roslaunch interbotix_xsarm_descriptions xsarm_description.launch robot_model:=wx200 robot_name:=wx200
```

Note that the wx200's space frame and body frame are `base_link` and `ee_gripper_link`, respectively.

Then write a script like below, making sure to replace the relevant names and variables.
```python3
from kinematics_from_description.kfd import KinematicsFromDescriptionTool as KFD

tool = KFD(
    {
        space_frame: SPACE_FRAME, # replace with name of the base link
        body_frame: BODY_FRAME, # replace with name of the end effector link
        namespace: NAMESPACE # replace with namespace of the robot
    }
)
tool.load_desc_from_param()
tool.run()

print('\nThe MR Descriptions are as follows:')

print("\nM:")
print(repr(tool.get_M()))

print("\nSlist:")
print(str(repr(tool.get_Slist(transposed=False))) + ".T\n")

print(
    (
        'Paste these arrays into your mr_descriptions.py file to use in the Interbotix '
        'Python-ROS API.'
    )
)
```

Check out the script [mr_desc_param](https://github.com/Interbotix/kinematics_from_description/blob/main/scripts/mr_desc_param) for usage details.

**Comment by lukeschmitt-tr** [comment]
Do you have any further questions on this? Otherwise, this issue will be closed.

**Comment by Jornsd** [comment]
No, thank you for the help!
